#Build Settings
#theme: jekyll-theme-cayman
remote_theme: "mmistakes/jekyll-theme-basically-basic"

title: Eric Fletcher
description: [A short description of your purpose]
lang: en-US
github_username: efletche

author:
  name: Eric Fletcher

collections:
  publications:
    output: true
    permalink: /:collection/:page/

defaults:
  # _publications
  - scope:
      path: "_publications"
      type: publications
    values:
      layout: post
      read_time: false
